### ISSUE TITLE
Use `.delay()` to Call CeleryTasks

### ISSUE THREAD

**Issue by pulgamecanica** [pulgamecanica/slidespeak-coding-challenge-2024#2]
### ⚙️ **Description**  
The Celery task `extract_videos_task` is defined but not properly utilized. Update the code to call the task using `.delay()` instead of directly invoking it.

***

### ⛔ **Dependency**  
This issue depends on #1  **Add Celery Worker to Docker Compose** being resolved. 
Only work on this after the dependencies have been marked as resolved.

***

### ✍ **Tasks**  
- Modify the `/extract` endpoint in `main.py` to call `extract_videos_task.delay()` instead of directly invoking the function.  
- Test the endpoint to ensure tasks are successfully enqueued and processed by the worker.  
- Handle and respond to task IDs or statuses in the API response.  

***

### 🎯 **Acceptance Criteria**  
- Task is enqueued using `.delay()` and processed by the Celery worker.  
- Proper response is returned to the client with task details.

**Comment by kgoedecke** [comment]
Additionally since you then introduce tasks you need an endpoint to check the task status since the frontend will then have to do polling using a task status endpoint. Example here: https://github.com/SlideSpeak/pptx-to-pdf-server/blob/main/fastapi_server/main.py#L38-L47

I hope that makes sense?

**Comment by pulgamecanica** [comment]
You're absolutely right—I'll add a `GET /get-result/{task_id}`  endpoint so the frontend can poll task statuses.

This will handle querying the Celery task result on the backend and cover scenarios like finished, invalid or failed tasks.
