### ISSUE TITLE
Zip Media Files for Easy Download

### ISSUE THREAD

**Issue by pulgamecanica** [pulgamecanica/slidespeak-coding-challenge-2024#4]
### 📦 **Description**  
Instead of returning presigned URLs for each video, zip all media files into a single archive and provide a download link. This improves usability by allowing users to download all videos at once.

***

### ✍ **Tasks**  
- Add functionality to create a ZIP archive of the extracted videos in `video_extractor.py`.  
- Upload the ZIP archive to S3 and return a presigned URL for the ZIP file.  
- Ensure the ZIP archive is removed after upload to save space.  

***

### 🎯 **Acceptance Criteria**  
- A single ZIP archive containing all media files is created and uploaded to S3.  
- API response includes a presigned URL for the ZIP archive.  
- Add a thorough documentation about the `POST /extract` endpoint response.

**Comment by kgoedecke** [comment]
@pulgamecanica this sounds good to me, obviously we only need to zip it if its more than 1 video. Otherwise the ACs look good to me 🚀
